import sympy as sp
from sympy.printing.c import ccode
from sympy.printing.numpy import JaxPrinter
import argparse
import sys
import importlib.util
import importlib
from pathlib import Path

# Add the project root to the Python path to allow finding the 'definitions' module
sys.path.append(str(Path(__file__).parent.resolve()))

from definitions.abc import Element, Material


# ---------------------------------------------------------------------------
# 数据容器 + 静态编译分发
# ---------------------------------------------------------------------------
class MathModel:
    """数据容器：存储数学定义"""
    def __init__(self, inputs, outputs, name="kernel", input_names=None, is_operator=False):
        self.inputs = inputs   # SymPy 符号列表
        self.outputs = outputs # SymPy 表达式列表
        self.name = name
        self.input_names = input_names or [str(s) for s in inputs]
        self.is_operator = is_operator # 是否作为算子生成（可能包含SIMD优化等）


class FEACompiler:
    @staticmethod
    def compile(model: MathModel, target: str):
        """
        核心分发器：输入 MathModel + target，输出 cpp/cuda/jax/peachpy 源码字符串。
        target: 'jax', 'cpp', 'cuda', 'peachpy'
        """
        target = target.lower()
        if target == 'jax':
            return FEACompiler._to_jax(model)
        elif target in ['cpp', 'c++']:
            return FEACompiler._to_source(model, is_cuda=False)
        elif target == 'cuda':
            return FEACompiler._to_source(model, is_cuda=True)
        elif target == 'peachpy':
            return FEACompiler._to_peachpy(model)
        else:
            raise ValueError(f"Unknown target: {target}")

    @staticmethod
    def compile_all(model: MathModel):
        """一次性生成 jax/cpp/cuda/peachpy 四种目标源码。"""
        return {
            "jax": FEACompiler._to_jax(model),
            "cpp": FEACompiler._to_source(model, is_cuda=False),
            "cuda": FEACompiler._to_source(model, is_cuda=True),
            "peachpy": FEACompiler._to_peachpy(model),
        }

    @staticmethod
    def _to_jax(model):
        """生成 JAX 源码（.py），采用分块 CSE 优化。"""
        # 对于 JAX，分块大小可以稍微大一点
        chunk_size = 50
        outputs = model.outputs
        
        lines = [
            '"""Generated by sympy_codegen.py. Do not edit."""',
            "import jax.numpy as jnp",
            "",
            "",
            f"def compute_{model.name}(in_flat):",
            f'    """in_flat: 扁平化输入, size {len(model.inputs)}。返回 {len(model.outputs)} 个元素。"""',
        ]
        
        # Unpack inputs IF they are valid identifiers (e.g. xi, c0)
        # If they are like "in[0]", we'll handle them via string replacement later
        for i, sym in enumerate(model.inputs):
            s = str(sym)
            is_ident = s.isidentifier()
            # print(f"DEBUG: sym={s}, is_ident={is_ident}")
            if is_ident:
                lines.append(f"    {s} = in_flat[{i}]")
        
        lines.append("")
        
        printer = JaxPrinter()
        all_simplified_outputs = []
        
        for i in range(0, len(outputs), chunk_size):
            chunk = outputs[i:i + chunk_size]
            sub_exprs, simplified_chunk = sp.cse(chunk, symbols=sp.numbered_symbols(f"v_{i//chunk_size}_"))
            
            for var, expr in sub_exprs:
                lines.append(f"    {var} = {printer.doprint(expr)}")
            
            all_simplified_outputs.extend(simplified_chunk)

        lines.append("")
        lines.append("    # --- Output ---")
        out_parts = [printer.doprint(e) for e in all_simplified_outputs]
        lines.append(f"    return ({','.join(out_parts)})")
        
        src = "\n".join(lines)
        # Final cleanup for JAX and handle C-style inputs
        src = src.replace("jax.numpy.", "jnp.").replace("in[", "in_flat[")
        return src

    @staticmethod
    def _to_source(model, is_cuda=False):
        """生成 C++/CUDA 源码，采用分块 CSE 优化及算子化增强。"""
        chunk_size = 24 # 默认分块大小，对应一行（对于 24x24 矩阵）
        outputs = model.outputs
        
        # --- Generate Comments ---
        comment_lines = ["/**"]
        comment_lines.append(f" * @brief Computes the {model.name} kernel.")
        if model.is_operator:
            comment_lines.append(" * @note This is an optimized operator kernel.")
        comment_lines.append(" * ")
        comment_lines.append(" * @param in Input array (const double*). Layout:")
        
        for i, name in enumerate(model.input_names):
            comment_lines.append(f" *   - in[{i}]: {name}")

        comment_lines.append(" * ")
        comment_lines.append(" * @param out Output array (double*). Layout:")
        comment_lines.append(f" *   - out[0..{len(model.outputs)-1}]: Flattened result, row-major order.")
        comment_lines.append(" */")
        comment_block = "\n".join(comment_lines)

        # --- Generate Function Body ---
        body_lines = []
        
        # 强制内存对齐提示 (针对 C++)
        if not is_cuda:
            # 对于现代编译器，我们可以提示输入输出是对齐的
            # body_lines.append("    const double* __restrict__ pin = (const double*)__builtin_assume_aligned(in, 64);")
            # body_lines.append("    double* __restrict__ pout = (double*)__builtin_assume_aligned(out, 64);")
            pass

        all_simplified_outputs = []
        
        for i in range(0, len(outputs), chunk_size):
            chunk = outputs[i:i + chunk_size]
            # 使用带编号的符号避免冲突
            sub_exprs, simplified_chunk = sp.cse(chunk, symbols=sp.numbered_symbols(f"v_{i//chunk_size}_"))
            
            body_lines.append(f"\n    // --- Chunk {i//chunk_size} ---")
            for var, expr in sub_exprs:
                body_lines.append(f"    double {var} = {ccode(expr)};")
            
            for j, out_expr in enumerate(simplified_chunk):
                body_lines.append(f"    out[{i + j}] = {ccode(out_expr)};")

        func_type = "__device__ void" if is_cuda else "inline void"
        if not is_cuda:
             # 添加编译器特定的向量化提示
             func_type = "[[gnu::always_inline]] " + func_type
        
        body = "\n".join(body_lines)
        
        return f"{comment_block}\n{func_type} compute_{model.name}(const double* __restrict__ in, double* __restrict__ out) {{ \n{body}\n}}"

    @staticmethod
    def _to_peachpy(model):
        """生成 PeachPy 源码 (.py)"""
        class PeachPyEmitter:
            def __init__(self, model):
                self.model = model
                self.model_name = model.name
                self.lines = [
                    '"""Generated by sympy_codegen.py. Do not edit."""',
                    "from peachpy import *",
                    "from peachpy.x86_64 import *",
                    "import re",
                    "",
                    "in_ptr = Argument(ptr(const_double_), name=\"in\")",
                    "out_ptr = Argument(ptr(double_), name=\"out\")",
                    "",
                    f"with Function(\"compute_{self.model_name}\", (in_ptr, out_ptr)) as function:",
                    "    reg_in = GeneralPurposeRegister64()",
                    "    reg_out = GeneralPurposeRegister64()",
                    "    LOAD.ARGUMENT(reg_in, in_ptr)",
                    "    LOAD.ARGUMENT(reg_out, out_ptr)",
                    "",
                    "    # Cache for input variables and constants",
                    "    v_map = {} # sym_obj -> register_name",
                    "    constants = {} # value -> register_name",
                    ""
                ]
                self.v_map = {} # sym_obj -> register_name
                self.constants = {}
                self.tmp_by_depth = {}

            def get_reg(self, sym, is_new=False):
                if sym not in self.v_map or is_new:
                    reg_name = f"v_{len(self.v_map)}"
                    self.lines.append(f"    {reg_name} = XMMRegister()")
                    self.v_map[sym] = reg_name
                return self.v_map[sym]

            def handle_const(self, val):
                val_f = float(val)
                if val_f not in self.constants:
                    reg = f"c_{len(self.constants)}"
                    self.lines.append(f"    {reg} = XMMRegister()")
                    self.lines.append(f"    MOVSD({reg}, Constant.float64({val_f}))")
                    self.constants[val_f] = reg
                return self.constants[val_f]

            def get_val_code(self, val):
                if val.is_Number:
                    return self.handle_const(val)
                
                if val in self.v_map:
                    return self.v_map[val]
                
                s_val = str(val)
                # Check for in[i] pattern
                if s_val.startswith("in["):
                    idx_str = s_val[3:-1]
                    if idx_str.isdigit():
                        return f"[reg_in + {int(idx_str)*8}]"

                import re
                match = re.match(r"in\[(\d+)\]", s_val)
                if match:
                    idx = int(match.group(1))
                    return f"[reg_in + {idx*8}]"

                # Check named inputs
                for idx, inp in enumerate(self.model.inputs):
                    if inp == val or str(inp) == s_val:
                        return f"[reg_in + {idx*8}]"
                
                return f"None # Error: {s_val} not found"

            def emit(self, line):
                self.lines.append(f"    {line}")

            def get_tmp(self, depth):
                if depth not in self.tmp_by_depth:
                    reg_name = f"tmp_d{depth}"
                    self.lines.append(f"    {reg_name} = XMMRegister()")
                    self.tmp_by_depth[depth] = reg_name
                return self.tmp_by_depth[depth]

            def finalize(self):
                self.lines.append("    RETURN()")
                self.lines.append("")
                return "\n".join(self.lines)

        emitter = PeachPyEmitter(model)
        outputs = model.outputs
        
        def _emit_recursive(e, target, depth=0):
            if e.is_Number or e.is_Symbol:
                emitter.emit(f"MOVSD({target}, {emitter.get_val_code(e)})")
            elif isinstance(e, sp.Add):
                _emit_recursive(e.args[0], target, depth)
                for a in e.args[1:]:
                    if a.is_Number or a.is_Symbol:
                        emitter.emit(f"ADDSD({target}, {emitter.get_val_code(a)})")
                    else:
                        tmp = emitter.get_tmp(depth + 1)
                        _emit_recursive(a, tmp, depth + 1)
                        emitter.emit(f"ADDSD({target}, {tmp})")
            elif isinstance(e, sp.Mul):
                _emit_recursive(e.args[0], target, depth)
                for a in e.args[1:]:
                    if a.is_Number or a.is_Symbol:
                        emitter.emit(f"MULSD({target}, {emitter.get_val_code(a)})")
                    else:
                        tmp = emitter.get_tmp(depth + 1)
                        _emit_recursive(a, tmp, depth + 1)
                        emitter.emit(f"MULSD({target}, {tmp})")
            elif isinstance(e, sp.Pow) and e.args[1] == 2:
                _emit_recursive(e.args[0], target, depth)
                emitter.emit(f"MULSD({target}, {target})")
            elif isinstance(e, sp.Pow) and e.args[1] == -1:
                emitter.emit(f"MOVSD({target}, {emitter.handle_const(1.0)})")
                if e.args[0].is_Number or e.args[0].is_Symbol:
                    emitter.emit(f"DIVSD({target}, {emitter.get_val_code(e.args[0])})")
                else:
                    tmp = emitter.get_tmp(depth + 1)
                    _emit_recursive(e.args[0], tmp, depth + 1)
                    emitter.emit(f"DIVSD({target}, {tmp})")
            else:
                emitter.emit(f"# Warning: Unsupported expression: {e}")

        tmp_out = emitter.get_tmp(0)
        for j, out_expr in enumerate(outputs):
            _emit_recursive(out_expr, tmp_out, 0)
            emitter.emit(f"MOVSD([reg_out + {j*8}], {tmp_out})")

        return emitter.finalize()

    @staticmethod
    def compile_element(element: Element, target: str):
        """
        Special compiler for Elements: supports both single-kernel and operator-based generation.
        """
        operators = element.get_stiffness_operators()
        if operators:
            # Generate multiple operator kernels
            generated = {}
            for op_model in operators:
                generated[op_model.name] = FEACompiler.compile(op_model, target)
            return generated
        else:
            # Traditional single kernel
            model = element.get_stiffness_model()
            return {model.name: FEACompiler.compile(model, target)}


# ---------------------------------------------------------------------------
# 动态模型加载
# ---------------------------------------------------------------------------
def _load_class(module_path: str, class_name: str):
    """动态加载类"""
    try:
        module = importlib.import_module(module_path)
        return getattr(module, class_name)
    except (ModuleNotFoundError, AttributeError) as e:
        raise ImportError(f"Could not find class '{class_name}' in module '{module_path}'.\nError: {e}")

def load_element(name: str) -> Element:
    """Loads an element class from the definitions.elements directory."""
    class_name = name.capitalize()
    module_path = f"definitions.elements.{name}"
    return _load_class(module_path, class_name)()

def load_material(name: str) -> Material:
    """Loads a material class from the definitions.materials directory."""
    class_name = name.capitalize()
    module_path = f"definitions.materials.{name}"
    return _load_class(module_path, class_name)()


def _default_output(model_name: str, target: str) -> str:
    t = target.lower()
    if t == "jax":
        return f"{model_name}_gen.py"
    if t in ("cpp", "c++"):
        return f"{model_name}_gen.cpp"
    if t == "cuda":
        return f"{model_name}_gen.cu"
    if t == "peachpy":
        return f"{model_name}_peachpy.py"
    return f"{model_name}_{t}.txt"

def main():
    parser = argparse.ArgumentParser(
        description="SymPy FEA 代码生成器 (混合解耦架构)"
    )
    parser.add_argument(
        "--task",
        required=True,
        choices=["constitutive", "stiffness", "mass", "custom"],
        help="生成任务: 'constitutive' (材料D矩阵), 'stiffness' (单元Ke矩阵), 'mass' (质量矩阵), 或 'custom' (自定义数学模型)",
    )
    parser.add_argument(
        "--element", "-e",
        help="单元名称 (e.g., 'tet4'), required for --task=stiffness",
    )
    parser.add_argument(
        "--material", "-m",
        help="材料名称 (e.g., 'isotropic'), required for --task=constitutive",
    )
    parser.add_argument(
        "--script", "-s",
        help="Python 脚本路径 (用于 --task=custom). 脚本中需要提供 get_model() 函数返回 MathModel.",
    )
    parser.add_argument(
        "--target", "-t",
        required=True,
        choices=["jax", "cpp", "cuda", "peachpy", "all"],
        help="目标语言：jax / cpp / cuda / peachpy / all",
    )
    parser.add_argument(
        "--output", "-o",
        default=None,
        help="输出文件路径（默认根据任务和名称生成）",
    )
    args = parser.parse_args()

    if args.task == "constitutive":
        if not args.material:
            parser.error("--material is required for --task=constitutive")
        material = load_material(args.material)
        model = material.get_constitutive_model()
        models_to_compile = {model.name: model}
        
    elif args.task == "stiffness":
        if not args.element:
            parser.error("--element is required for --task=stiffness")
        element = load_element(args.element)
        operators = element.get_stiffness_operators()
        if operators:
            models_to_compile = {op.name: op for op in operators}
        else:
            m = element.get_stiffness_model()
            models_to_compile = {m.name: m}

    elif args.task == "mass":
        if not args.element:
            parser.error("--element is required for --task=mass")
        element = load_element(args.element)
        operators = element.get_mass_operators()
        if operators:
            models_to_compile = {op.name: op for op in operators}
        else:
            # Fallback if no specific mass model is defined, though mass usually has operators
            parser.error(f"No mass operators defined for element: {args.element}")
            
    elif args.task == "custom":
        if not args.script:
            parser.error("--script is required for --task=custom")
        script_path = Path(args.script)
        if not script_path.exists():
            parser.error(f"Script file not found: {script_path}")
            
        # Dynamically load the script
        spec = importlib.util.spec_from_file_location("custom_script", str(script_path))
        custom_mod = importlib.util.module_from_spec(spec)
        sys.modules["custom_script"] = custom_mod
        spec.loader.exec_module(custom_mod)
        
        if not hasattr(custom_mod, "get_model"):
            parser.error(f"Script {script_path} must define a 'get_model()' function.")
            
        models = custom_mod.get_model()
        if type(models).__name__ == "MathModel":
            models_to_compile = {models.name: models}
        elif isinstance(models, list) and all(type(m).__name__ == "MathModel" for m in models):
            models_to_compile = {m.name: m for m in models}
        else:
            parser.error(f"get_model() must return a MathModel or a list of MathModels. Got: {type(models)}")

    # ---------------- Compile Models ----------------
    target = args.target
    targets = ["jax", "cpp", "cuda"] if target == "all" else [target]
    
    for name, model in models_to_compile.items():
        for t in targets:
            code = FEACompiler.compile(model, t)
            out_path = Path(args.output or ".") / _default_output(name, t)
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(code)
            print(f"Generated: {out_path}")


if __name__ == "__main__":
    main()
