import sympy as sp
from sympy.printing.c import ccode
from sympy.printing.numpy import JaxPrinter
import argparse
import sys
import importlib
from pathlib import Path

# Add the project root to the Python path to allow finding the 'definitions' module
sys.path.append(str(Path(__file__).parent.resolve()))

from definitions.abc import Element, Material


# ---------------------------------------------------------------------------
# 数据容器 + 静态编译分发
# ---------------------------------------------------------------------------
class MathModel:
    """数据容器：存储数学定义"""
    def __init__(self, inputs, outputs, name="kernel", input_names=None, is_operator=False):
        self.inputs = inputs   # SymPy 符号列表
        self.outputs = outputs # SymPy 表达式列表
        self.name = name
        self.input_names = input_names or [str(s) for s in inputs]
        self.is_operator = is_operator # 是否作为算子生成（可能包含SIMD优化等）


class FEACompiler:
    @staticmethod
    def compile(model: MathModel, target: str):
        """
        核心分发器：输入 MathModel + target，输出 cpp/cuda/jax 源码字符串。
        target: 'jax', 'cpp', 'cuda'
        """
        target = target.lower()
        if target == 'jax':
            return FEACompiler._to_jax(model)
        elif target in ['cpp', 'c++']:
            return FEACompiler._to_source(model, is_cuda=False)
        elif target == 'cuda':
            return FEACompiler._to_source(model, is_cuda=True)
        else:
            raise ValueError(f"Unknown target: {target}")

    @staticmethod
    def compile_all(model: MathModel):
        """一次性生成 jax/cpp/cuda 三种目标源码。"""
        return {
            "jax": FEACompiler._to_jax(model),
            "cpp": FEACompiler._to_source(model, is_cuda=False),
            "cuda": FEACompiler._to_source(model, is_cuda=True),
        }

    @staticmethod
    def _to_jax(model):
        """生成 JAX 源码（.py），采用分块 CSE 优化。"""
        # 对于 JAX，分块大小可以稍微大一点
        chunk_size = 50
        outputs = model.outputs
        
        lines = [
            '"""Generated by sympy_codegen.py. Do not edit."""',
            "import jax.numpy as jnp",
            "",
            "",
            f"def compute_{model.name}(in_flat):",
            f'    """in_flat: 扁平化输入, size {len(model.inputs)}。返回 {len(model.outputs)} 个元素。"""',
        ]
        
        # Unpack inputs IF they are valid identifiers (e.g. xi, c0)
        # If they are like "in[0]", we'll handle them via string replacement later
        for i, sym in enumerate(model.inputs):
            s = str(sym)
            is_ident = s.isidentifier()
            # print(f"DEBUG: sym={s}, is_ident={is_ident}")
            if is_ident:
                lines.append(f"    {s} = in_flat[{i}]")
        
        lines.append("")
        
        printer = JaxPrinter()
        all_simplified_outputs = []
        
        for i in range(0, len(outputs), chunk_size):
            chunk = outputs[i:i + chunk_size]
            sub_exprs, simplified_chunk = sp.cse(chunk, symbols=sp.numbered_symbols(f"v_{i//chunk_size}_"))
            
            for var, expr in sub_exprs:
                lines.append(f"    {var} = {printer.doprint(expr)}")
            
            all_simplified_outputs.extend(simplified_chunk)

        lines.append("")
        lines.append("    # --- Output ---")
        out_parts = [printer.doprint(e) for e in all_simplified_outputs]
        lines.append(f"    return ({','.join(out_parts)})")
        
        src = "\n".join(lines)
        # Final cleanup for JAX and handle C-style inputs
        src = src.replace("jax.numpy.", "jnp.").replace("in[", "in_flat[")
        return src

    @staticmethod
    def _to_source(model, is_cuda=False):
        """生成 C++/CUDA 源码，采用分块 CSE 优化及算子化增强。"""
        chunk_size = 24 # 默认分块大小，对应一行（对于 24x24 矩阵）
        outputs = model.outputs
        
        # --- Generate Comments ---
        comment_lines = ["/**"]
        comment_lines.append(f" * @brief Computes the {model.name} kernel.")
        if model.is_operator:
            comment_lines.append(" * @note This is an optimized operator kernel.")
        comment_lines.append(" * ")
        comment_lines.append(" * @param in Input array (const double*). Layout:")
        
        for i, name in enumerate(model.input_names):
            comment_lines.append(f" *   - in[{i}]: {name}")

        comment_lines.append(" * ")
        comment_lines.append(" * @param out Output array (double*). Layout:")
        comment_lines.append(f" *   - out[0..{len(model.outputs)-1}]: Flattened result, row-major order.")
        comment_lines.append(" */")
        comment_block = "\n".join(comment_lines)

        # --- Generate Function Body ---
        body_lines = []
        
        # 强制内存对齐提示 (针对 C++)
        if not is_cuda:
            # 对于现代编译器，我们可以提示输入输出是对齐的
            # body_lines.append("    const double* __restrict__ pin = (const double*)__builtin_assume_aligned(in, 64);")
            # body_lines.append("    double* __restrict__ pout = (double*)__builtin_assume_aligned(out, 64);")
            pass

        all_simplified_outputs = []
        
        for i in range(0, len(outputs), chunk_size):
            chunk = outputs[i:i + chunk_size]
            # 使用带编号的符号避免冲突
            sub_exprs, simplified_chunk = sp.cse(chunk, symbols=sp.numbered_symbols(f"v_{i//chunk_size}_"))
            
            body_lines.append(f"\n    // --- Chunk {i//chunk_size} ---")
            for var, expr in sub_exprs:
                body_lines.append(f"    double {var} = {ccode(expr)};")
            
            for j, out_expr in enumerate(simplified_chunk):
                body_lines.append(f"    out[{i + j}] = {ccode(out_expr)};")

        func_type = "__device__ void" if is_cuda else "inline void"
        if not is_cuda:
             # 添加编译器特定的向量化提示
             func_type = "[[gnu::always_inline]] " + func_type
        
        body = "\n".join(body_lines)
        
        return f"{comment_block}\n{func_type} compute_{model.name}(const double* __restrict__ in, double* __restrict__ out) {{ \n{body}\n}}"

    @staticmethod
    def compile_element(element: Element, target: str):
        """
        Special compiler for Elements: supports both single-kernel and operator-based generation.
        """
        operators = element.get_stiffness_operators()
        if operators:
            # Generate multiple operator kernels
            generated = {}
            for op_model in operators:
                generated[op_model.name] = FEACompiler.compile(op_model, target)
            return generated
        else:
            # Traditional single kernel
            model = element.get_stiffness_model()
            return {model.name: FEACompiler.compile(model, target)}


# ---------------------------------------------------------------------------
# 动态模型加载
# ---------------------------------------------------------------------------
def _load_class(module_path: str, class_name: str):
    """动态加载类"""
    try:
        module = importlib.import_module(module_path)
        return getattr(module, class_name)
    except (ModuleNotFoundError, AttributeError) as e:
        raise ImportError(f"Could not find class '{class_name}' in module '{module_path}'.\nError: {e}")

def load_element(name: str) -> Element:
    """Loads an element class from the definitions.elements directory."""
    class_name = name.capitalize()
    module_path = f"definitions.elements.{name}"
    return _load_class(module_path, class_name)()

def load_material(name: str) -> Material:
    """Loads a material class from the definitions.materials directory."""
    class_name = name.capitalize()
    module_path = f"definitions.materials.{name}"
    return _load_class(module_path, class_name)()


def _default_output(model_name: str, target: str) -> str:
    t = target.lower()
    if t == "jax":
        return f"{model_name}_gen.py"
    if t in ("cpp", "c++"):
        return f"{model_name}_gen.cpp"
    if t == "cuda":
        return f"{model_name}_gen.cu"
    return f"{model_name}_{t}.txt"

def main():
    parser = argparse.ArgumentParser(
        description="SymPy FEA 代码生成器 (混合解耦架构)"
    )
    parser.add_argument(
        "--task",
        required=True,
        choices=["constitutive", "stiffness"],
        help="生成任务: 'constitutive' (材料D矩阵) 或 'stiffness' (单元Ke矩阵)",
    )
    parser.add_argument(
        "--element", "-e",
        help="单元名称 (e.g., 'tet4'), required for --task=stiffness",
    )
    parser.add_argument(
        "--material", "-m",
        help="材料名称 (e.g., 'isotropic'), required for --task=constitutive",
    )
    parser.add_argument(
        "--target", "-t",
        required=True,
        choices=["jax", "cpp", "cuda", "all"],
        help="目标语言：jax / cpp / cuda / all",
    )
    parser.add_argument(
        "--output", "-o",
        default=None,
        help="输出文件路径（默认根据任务和名称生成）",
    )
    args = parser.parse_args()

    if args.task == "constitutive":
        if not args.material:
            parser.error("--material is required for --task=constitutive")
        material = load_material(args.material)
        model = material.get_constitutive_model()
        
        target = args.target
        if target == "all":
            generated = FEACompiler.compile_all(model)
            for t, code in generated.items():
                out_path = Path(args.output or ".") / _default_output(model.name, t)
                with open(out_path, "w", encoding="utf-8") as f:
                    f.write(code)
                print(f"Generated: {out_path}")
        else:
            out_path = args.output or _default_output(model.name, target)
            code = FEACompiler.compile(model, target)
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(code)
            print(f"Generated: {out_path}")

    elif args.task == "stiffness":
        if not args.element:
            parser.error("--element is required for --task=stiffness")
        element = load_element(args.element)
        
        target = args.target
        targets = ["jax", "cpp", "cuda"] if target == "all" else [target]
        
        for t in targets:
            kernels = FEACompiler.compile_element(element, t)
            for name, code in kernels.items():
                out_path = Path(args.output or ".") / _default_output(name, t)
                with open(out_path, "w", encoding="utf-8") as f:
                    f.write(code)
                print(f"Generated: {out_path}")


if __name__ == "__main__":
    main()
