import sympy as sp
from sympy.printing.c import ccode
from sympy.printing.numpy import JaxPrinter
import argparse
import sys


# ---------------------------------------------------------------------------
# 数据容器 + 静态编译分发
# ---------------------------------------------------------------------------
class MathModel:
    """数据容器：存储数学定义"""
    def __init__(self, inputs, outputs, name="kernel"):
        self.inputs = inputs   # SymPy 符号列表
        self.outputs = outputs # SymPy 表达式列表
        self.name = name


class FEACompiler:
    @staticmethod
    def compile(model: MathModel, target: str):
        """
        核心分发器：输入 MathModel + target，输出 cpp/cuda/jax 源码字符串。
        target: 'jax', 'cpp', 'cuda'
        """
        target = target.lower()
        if target == 'jax':
            return FEACompiler._to_jax(model)
        elif target in ['cpp', 'c++']:
            return FEACompiler._to_source(model, is_cuda=False)
        elif target == 'cuda':
            return FEACompiler._to_source(model, is_cuda=True)
        else:
            raise ValueError(f"Unknown target: {target}")

    @staticmethod
    def compile_all(model: MathModel):
        """一次性生成 jax/cpp/cuda 三种目标源码。"""
        return {
            "jax": FEACompiler._to_jax(model),
            "cpp": FEACompiler._to_source(model, is_cuda=False),
            "cuda": FEACompiler._to_source(model, is_cuda=True),
        }

    @staticmethod
    def _to_jax(model):
        """生成 JAX 源码（.py），与 C++ 一致：由 MathModel.outputs 经 CSE 展开生成。"""
        sub_exprs, simplified_outputs = sp.cse(model.outputs)
        printer = JaxPrinter()
        lines = [
            '"""Generated by sympy_codegen_tet4. Do not edit."""',
            "import jax.numpy as jnp",
            "",
            "",
            f"def compute_{model.name}(in_flat):",
            '    """in_flat: 与 C/CUDA 一致的扁平输入 (coords 12 + D 36)。返回 144 个 Ke 元素。"""',
        ]
        for var, expr in sub_exprs:
            lines.append(f"    {var} = {printer.doprint(expr)}")
        lines.append("")
        lines.append("    # --- Output ---")
        out_parts = [printer.doprint(e) for e in simplified_outputs]
        lines.append(f"    return ({','.join(out_parts)})")
        src = "\n".join(lines)
        src = src.replace("jax.numpy.", "jnp.").replace("in[", "in_flat[")
        return src

    @staticmethod
    def _to_source(model, is_cuda=False):
        sub_exprs, simplified_outputs = sp.cse(model.outputs)

        lines = []
        for var, expr in sub_exprs:
            lines.append(f"    double {var} = {ccode(expr)};")

        lines.append("\n    // --- Output Assignment ---")

        for i, out_expr in enumerate(simplified_outputs):
            lines.append(f"    out[{i}] = {ccode(out_expr)};")

        func_type = "__device__ void" if is_cuda else "inline void"
        body = "\n".join(lines)
        return f"{func_type} compute_{model.name}(const double* in, double* out) {{\n{body}\n}}"


# ---------------------------------------------------------------------------
# Tet4 单元刚度数学模型（与 tet4_jax.compute_tet4_K_decoupled 一致）
# 输入：坐标 coords (4x3) + 本构矩阵 D (6x6)；展平为 in[0..47] 供 C/CUDA
# 输出：Ke (12x12) 展平 144 个表达式
# ---------------------------------------------------------------------------
def get_tet4_math():
    """定义 Tet4 刚度矩阵的数学逻辑：输入为坐标 + D 矩阵，算法同 tet4_jax。"""
    # 输入：坐标 (4x3) + D (6x6)，展平为 in[0..47] 以匹配 C/CUDA kernel 的 const double* in
    in_syms = [sp.Symbol(f"in[{i}]", real=True) for i in range(12 + 36)]
    coords = sp.Matrix(4, 3, lambda i, j: in_syms[i * 3 + j])
    D = sp.Matrix(6, 6, lambda i, j: in_syms[12 + i * 6 + j])

    # 母单元形函数 N（与 tet4_jax.get_N 一致），再求 dN/d_xi
    xi, eta, zeta = sp.symbols("xi eta zeta", real=True)
    N_list = [1 - xi - eta - zeta, xi, eta, zeta]
    dN_dxi = sp.Matrix(4, 3, lambda i, j: sp.diff(N_list[i], (xi, eta, zeta)[j]))

    # J = coords^T @ dN_dxi，vol = |det(J)|/6（与 jnp.abs(detJ)/6 一致）
    J = coords.T * dN_dxi
    detJ = J.det()
    vol = sp.Abs(detJ) / 6.0

    invJ = J.inv()
    dN_dx = dN_dxi * invJ

    B = sp.zeros(6, 12)
    for i in range(4):
        B[0, 3 * i] = dN_dx[i, 0]
        B[1, 3 * i + 1] = dN_dx[i, 1]
        B[2, 3 * i + 2] = dN_dx[i, 2]
        B[3, 3 * i] = dN_dx[i, 1]
        B[3, 3 * i + 1] = dN_dx[i, 0]
        B[4, 3 * i + 1] = dN_dx[i, 2]
        B[4, 3 * i + 2] = dN_dx[i, 1]
        B[5, 3 * i] = dN_dx[i, 2]
        B[5, 3 * i + 2] = dN_dx[i, 0]

    K = B.T * D * B * vol
    K_flat = [K[i, j] for i in range(12) for j in range(12)]

    return MathModel(inputs=in_syms, outputs=K_flat, name="tet4_Ke")


# ---------------------------------------------------------------------------
# 模型注册：供命令行选择
# ---------------------------------------------------------------------------
_MODELS = {
    "tet4": get_tet4_math,
}


def _get_model(name: str) -> MathModel:
    if name not in _MODELS:
        raise ValueError(f"Unknown model: {name}. Available: {list(_MODELS)}")
    return _MODELS[name]()


def _default_output(model_name: str, target: str) -> str:
    t = target.lower()
    if t == "jax":
        return f"{model_name}_gen.py"
    if t in ("cpp", "c++"):
        return f"{model_name}_gen.cpp"
    if t == "cuda":
        return f"{model_name}_gen.cu"
    return f"{model_name}_{t}.txt"


def main():
    parser = argparse.ArgumentParser(
        description="SymPy FEA 代码生成：输入 MathModel + target，输出 cpp/cuda/jax 源码文件。"
    )
    parser.add_argument(
        "--model", "-m",
        default="tet4",
        choices=list(_MODELS),
        help="数学模型（默认: tet4）",
    )
    parser.add_argument(
        "--target", "-t",
        required=True,
        choices=["jax", "cpp", "cuda", "all"],
        help="目标：jax / cpp / cuda / all",
    )
    parser.add_argument(
        "--output", "-o",
        default=None,
        help="输出文件路径（默认根据 model+target 生成）",
    )
    args = parser.parse_args()

    model = _get_model(args.model)
    target = args.target
    if target == "all":
        if args.output is None:
            out_base = "."
        else:
            out_base = args.output
        out_dir = out_base
        generated = FEACompiler.compile_all(model)
        outputs = {
            "jax": f"{args.model}_gen.py",
            "cpp": f"{args.model}_gen.cpp",
            "cuda": f"{args.model}_gen.cu",
        }
        for t, code in generated.items():
            out_path = f"{out_dir.rstrip('/\\')}/{outputs[t]}"
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(code)
            print(out_path)
    else:
        out_path = args.output or _default_output(args.model, target)
        code = FEACompiler.compile(model, target)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(code)
        print(out_path)


if __name__ == "__main__":
    main()
